<a href="https://colab.research.google.com/github/elevit/JuliaTest/blob/main/MyChapter_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%%shell
set -e

#---------------------------------------------------#
JULIA_VERSION="1.5.3" # any version ≥ 0.7.0
JULIA_PACKAGES="IJulia BenchmarkTools PyCall PyPlot"
JULIA_PACKAGES_IF_GPU="CUDA"
JULIA_NUM_THREADS=4
#---------------------------------------------------#

if [ -n "$COLAB_GPU" ] && [ -z `which julia` ]; then
  # Install Julia
  JULIA_VER=`cut -d '.' -f -2 <<< "$JULIA_VERSION"`
  echo "Installing Julia $JULIA_VERSION on the current Colab Runtime..."
  BASE_URL="https://julialang-s3.julialang.org/bin/linux/x64"
  URL="$BASE_URL/$JULIA_VER/julia-$JULIA_VERSION-linux-x86_64.tar.gz"
  wget -nv $URL -O /tmp/julia.tar.gz # -nv means "not verbose"
  tar -x -f /tmp/julia.tar.gz -C /usr/local --strip-components 1
  rm /tmp/julia.tar.gz

  # Install Packages
  if [ "$COLAB_GPU" = "1" ]; then
      JULIA_PACKAGES="$JULIA_PACKAGES $JULIA_PACKAGES_IF_GPU"
  fi
  for PKG in `echo $JULIA_PACKAGES`; do
    echo "Installing Julia package $PKG..."
    julia -e 'using Pkg; pkg"add '$PKG'; precompile;"'
  done

  # Install kernel and rename it to "julia"
  echo "Installing IJulia kernel..."
  julia -e 'using IJulia; IJulia.installkernel("julia", env=Dict(
      "JULIA_NUM_THREADS"=>"'"$JULIA_NUM_THREADS"'"))'
  KERNEL_DIR=`julia -e "using IJulia; print(IJulia.kerneldir())"`
  KERNEL_NAME=`ls -d "$KERNEL_DIR"/julia*`
  mv -f $KERNEL_NAME "$KERNEL_DIR"/julia  

  echo ''
  echo "Successfully installed `julia -v`!"
  echo "Please reload this page (press Ctrl+R, ⌘+R, or the F5 key) then"
  echo "jump to the 'Checking the Installation' section."
fi

Installing Julia 1.5.3 on the current Colab Runtime...
2021-01-03 21:51:03 URL:https://storage.googleapis.com/julialang2/bin/linux/x64/1.5/julia-1.5.3-linux-x86_64.tar.gz [105260711/105260711] -> "/tmp/julia.tar.gz" [1]
Installing Julia package IJulia...
 Installing known registries into `~/.julia`
######################################################################## 100.0%
      Added registry `General` to `~/.julia/registries/General`
  Resolving package versions...
  Installed Conda ─────────── v1.5.0
  Installed IJulia ────────── v1.23.1
  Installed MbedTLS ───────── v1.0.3
  Installed JLLWrappers ───── v1.1.4
  Installed Artifacts ─────── v1.3.0
  Installed ZMQ ───────────── v1.2.1
  Installed ZeroMQ_jll ────── v4.3.2+5
  Installed SoftGlobalScope ─ v1.1.0
  Installed VersionParsing ── v1.2.0
  Installed Parsers ───────── v1.0.15
  Installed JSON ──────────── v0.21.1
  Installed MbedTLS_jll ───── v2.16.8+1
########################################################################

In [1]:
using Pkg
pkg"activate ."

 Activating new environment at `/content/Project.toml`


In [2]:
# Run this cell in order to download all the package dependencies with the exact versions used in the book
# This is necessary if (some of) the packages have been updated and have introduced breaking changes
pkg"instantiate"

   Updating registry at `~/.julia/registries/General`
No Changes to `/content/Project.toml`
No Changes to `/content/Manifest.toml`


In [3]:
book = "Julia v1.0 By Example"

"Julia v1.0 By Example"

In [4]:
pi = 3.14

3.14

In [5]:
ANSWER = 42

42

In [6]:
my_first_name = "Adrian"

"Adrian"

In [7]:
answer

LoadError: ignored

In [8]:
δ = 130

130

In [9]:
🚀 = "apollo 11"

"apollo 11"

In [ ]:
do = 3

In [ ]:
end = "Paris"

In [ ]:
MysteryVar

In [ ]:
const firstmonth = "January"

In [ ]:
const mealoption = "vegetarian"

In [ ]:
mealoption = "vegan"

In [ ]:
mealoption = 2

In [ ]:
const amount = 10.25

In [ ]:
amount = 10

In [ ]:
amount = 10.00

In [ ]:
#=
	Our company charges a fixed 
	$10 fee per transaction.
=#
const flatfee = 10 # flat fee, per transaction 

In [10]:
"Measuring programming progress by lines of code is like measuring air-craft building progress by weight."

"Measuring programming progress by lines of code is like measuring air-craft building progress by weight."

In [ ]:
"Beta is Latin for \"still doesn’t work\"."

In [ ]:
"""Beta is Latin for "still doesn’t work"."""

In [ ]:
"""Beta is Latin for "still doesn’t work""""

In [ ]:
"""
  			Hello
  		Look
  	Here"""

In [11]:
string("Itsy", " ", "Bitsy", " ", "Spider")

"Itsy Bitsy Spider"

In [12]:
username = "Adrian"
greeting = "Good morning"
greeting * ", " * username

"Good morning, Adrian"

In [ ]:
username = 9543794
greeting = "Good morning"
greeting * ", " * username

In [13]:
username = 9543794
greeting = "Good morning"
string(greeting, ", ", username)

"Good morning, 9543794"

In [ ]:
username = "Adrian"
greeting = "Good morning"
"$greeting, $username"

In [ ]:
"$(uppercase(greeting)), $(reverse(username))"

In [ ]:
"The sum of 1 and 2 is $(1 + 2)"

In [15]:
str = "Nice to see you"

"Nice to see you"

In [16]:
str[1]

'N': ASCII/Unicode U+004E (category Lu: Letter, uppercase)

In [17]:
str[9:11]

"see"

In [18]:
str = "Søren Kierkegaard was a Danish Philosopher"

"Søren Kierkegaard was a Danish Philosopher"

In [ ]:
str[1]

In [ ]:
str[2]

In [ ]:
str[3]

In [ ]:
str[4]

In [19]:
nextind(str, 2)

4

In [20]:
for s in str
    println(s)
end

S
ø
r
e
n
 
K
i
e
r
k
e
g
a
a
r
d
 
w
a
s
 
a
 
D
a
n
i
s
h
 
P
h
i
l
o
s
o
p
h
e
r


In [21]:
length(str)

42

In [22]:
str[42]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [ ]:
str[end]

In [ ]:
str[end-10:end]

In [ ]:
str[end+1]

In [ ]:
reg = r"[0-9]+"

In [ ]:
match(reg, "It was 1970")

In [ ]:
typeof(reg)

In [ ]:
Regex("[0-9]+")

In [25]:
match(r"it was", "It was 1970") # case-sensitive no match

In [24]:
match(r"it was"i, "It was 1970") # case-insensitive match

RegexMatch("It was")

In [26]:
if match(r"it was", "It was 1970") !== nothing
   println("it's a match")
else
   println("not a match")
end

not a match


In [27]:
occursin(r"19", "It was 1970")

true

In [28]:
alice_in_wonderland = "Why, sometimes I've believed as many as six impossible things before breakfast."

"Why, sometimes I've believed as many as six impossible things before breakfast."

In [29]:
m = match(r"(\w+)+", alice_in_wonderland)

RegexMatch("Why", 1="Why")

In [30]:
m = match(r"(\w+)+", alice_in_wonderland, 6)

RegexMatch("sometimes", 1="sometimes")

In [31]:
m = match(r"((\w+)(\s+|\W+))", alice_in_wonderland)

RegexMatch("Why, ", 1="Why, ", 2="Why", 3=", ")

In [32]:
m.match

"Why, "

In [33]:
m.captures

3-element Array{Union{Nothing, SubString{String}},1}:
 "Why, "
 "Why"
 ", "

In [34]:
m.offset

1

In [35]:
m.offsets

3-element Array{Int64,1}:
 1
 1
 4

In [36]:
for m in eachmatch(r"((\w+)(\s+|\W+))", alice_in_wonderland)
   println(m)
end

RegexMatch("Why, ", 1="Why, ", 2="Why", 3=", ")
RegexMatch("sometimes ", 1="sometimes ", 2="sometimes", 3=" ")
RegexMatch("I'", 1="I'", 2="I", 3="'")
RegexMatch("ve ", 1="ve ", 2="ve", 3=" ")
RegexMatch("believed ", 1="believed ", 2="believed", 3=" ")
RegexMatch("as ", 1="as ", 2="as", 3=" ")
RegexMatch("many ", 1="many ", 2="many", 3=" ")
RegexMatch("as ", 1="as ", 2="as", 3=" ")
RegexMatch("six ", 1="six ", 2="six", 3=" ")
RegexMatch("impossible ", 1="impossible ", 2="impossible", 3=" ")
RegexMatch("things ", 1="things ", 2="things", 3=" ")
RegexMatch("before ", 1="before ", 2="before", 3=" ")
RegexMatch("breakfast.", 1="breakfast.", 2="breakfast", 3=".")


In [37]:
collect(eachmatch(r"((\w+)(\s+|\W+))", alice_in_wonderland))

13-element Array{RegexMatch,1}:
 RegexMatch("Why, ", 1="Why, ", 2="Why", 3=", ")
 RegexMatch("sometimes ", 1="sometimes ", 2="sometimes", 3=" ")
 RegexMatch("I'", 1="I'", 2="I", 3="'")
 RegexMatch("ve ", 1="ve ", 2="ve", 3=" ")
 RegexMatch("believed ", 1="believed ", 2="believed", 3=" ")
 RegexMatch("as ", 1="as ", 2="as", 3=" ")
 RegexMatch("many ", 1="many ", 2="many", 3=" ")
 RegexMatch("as ", 1="as ", 2="as", 3=" ")
 RegexMatch("six ", 1="six ", 2="six", 3=" ")
 RegexMatch("impossible ", 1="impossible ", 2="impossible", 3=" ")
 RegexMatch("things ", 1="things ", 2="things", 3=" ")
 RegexMatch("before ", 1="before ", 2="before", 3=" ")
 RegexMatch("breakfast.", 1="breakfast.", 2="breakfast", 3=".")

In [38]:
"This $will error out"

LoadError: ignored

In [39]:
raw"This $will work"

"This \$will work"

In [40]:
typeof(42)

Int64

In [41]:
@show Int

Int = Int64


Int64

In [42]:
typemin(Int), typemax(Int)

(-9223372036854775808, 9223372036854775807)

In [43]:
typemin(Int) - 1

9223372036854775807

In [44]:
BigInt(typemax(Int)) + 1

9223372036854775808

In [46]:
1//2 + 2//4

1//1

In [47]:
Int(1//1)

1

In [50]:
float(1//3)

0.3333333333333333

In [49]:
Int(1//3)

LoadError: ignored

In [51]:
float(1//3) == 1/3
true

true

In [ ]:
a = 2

In [ ]:
a *= 3 # equivalent of a = a * 3

In [ ]:
a ^= 2 # equivalent of a = a ^ 2

In [ ]:
a += 4 # equivalent of a = a + 4

In [ ]:
10 > 5 < 6 == 6 >= 3 != 2

In [52]:
first_five_fib = [1, 1, 2, 3, 5]

5-element Array{Int64,1}:
 1
 1
 2
 3
 5

In [ ]:
first_five_fib .^ 2

In [ ]:
first_five_fib

In [53]:
first_five_fib .^= 2

5-element Array{Int64,1}:
  1
  1
  4
  9
 25

In [54]:
first_five_fib

5-element Array{Int64,1}:
  1
  1
  4
  9
 25

In [55]:
(1,2,3)

(1, 2, 3)

In [56]:
("a", 4, 12.5)

("a", 4, 12.5)

In [57]:
(1,)

(1,)

In [58]:
'e', 2

('e', 2)

In [ ]:
1,

In [59]:
lang = ("Julia", v"1.0")
lang[2]

v"1.0.0"

In [60]:
(3,4) .+ (1,1)

(4, 5)

In [61]:
skills = (language = "Julia", experience = "Beginner", version = v"1.0")

(language = "Julia", experience = "Beginner", version = v"1.0.0")

In [62]:
skills.language

"Julia"

In [63]:
r = 1:20

1:20

In [64]:
abc = 'a':'z'

'a':1:'z'

In [65]:
abc[10]

'j': ASCII/Unicode U+006A (category Ll: Letter, lowercase)

In [66]:
abc[end]

'z': ASCII/Unicode U+007A (category Ll: Letter, lowercase)

In [67]:
(1:20...,)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [68]:
[1:20...]

20-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

In [69]:
(0:5:20...,)

(0, 5, 10, 15, 20)

In [70]:
(20:-5:-20...,)

(20, 15, 10, 5, 0, -5, -10, -15, -20)

In [71]:
(0.5:10)

0.5:1.0:9.5

In [ ]:
(0.5:10...,)

In [72]:
collect(0.5:0.5:10)

20-element Array{Float64,1}:
  0.5
  1.0
  1.5
  2.0
  2.5
  3.0
  3.5
  4.0
  4.5
  5.0
  5.5
  6.0
  6.5
  7.0
  7.5
  8.0
  8.5
  9.0
  9.5
 10.0

In [73]:
[1, 2, 3] 

3-element Array{Int64,1}:
 1
 2
 3

In [74]:
Float32[1, 2, 3, 4]

4-element Array{Float32,1}:
 1.0
 2.0
 3.0
 4.0

In [75]:
[1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [77]:
[1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [78]:
Vector(5)

LoadError: ignored

In [79]:
zeros(Int, 2)

2-element Array{Int64,1}:
 0
 0

In [80]:
zeros(Float64, 3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [81]:
ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [82]:
ones(Int, 2)

2-element Array{Int64,1}:
 1
 1

In [83]:
trues(2)

2-element BitArray{1}:
 1
 1

In [84]:
rand(Int, 4, 2)

4×2 Array{Int64,2}:
 -7068694176921190653  4960262959846582551
  8194176247288788531  8846244447402050132
 -8284478560000918054  1165197921916409658
   864358085284798918  2650379617154532438

In [85]:
rand(Char, 3, 2)

3×2 Array{Char,2}:
 '\U7943e'  '쎻'
 '\Uc3a19'  '\U4cc21'
 '\U70fbc'  '\U81ab7'

In [ ]:
fill(42, 2, 3)

In [86]:
arr1d = rand(5)

5-element Array{Float64,1}:
 0.6177171866796052
 0.33147317430406353
 0.7982726867234855
 0.3603008568055621
 0.7807351825166624

In [87]:
arr1d[5]

0.7807351825166624

In [88]:
arr2d = rand(5,2)

5×2 Array{Float64,2}:
 0.651124   0.0616876
 0.594894   0.0582643
 0.0325286  0.348522
 0.709623   0.545864
 0.455947   0.207822

In [90]:
arr2d[4, 1]

0.7096232238755227

In [91]:
arr2d = rand(5,5)

5×5 Array{Float64,2}:
 0.544344  0.999666  0.0104643  0.232791  0.0600055
 0.964799  0.811172  0.686232   0.6783    0.458559
 0.332513  0.531909  0.956483   0.386263  0.913086
 0.481364  0.288425  0.688278   0.827451  0.775269
 0.428898  0.863212  0.609029   0.779431  0.956487

In [92]:
arr2d[1:3, 3:5]

3×3 Array{Float64,2}:
 0.0104643  0.232791  0.0600055
 0.686232   0.6783    0.458559
 0.956483   0.386263  0.913086

In [93]:
arr2d[:, 3:5]

5×3 Array{Float64,2}:
 0.0104643  0.232791  0.0600055
 0.686232   0.6783    0.458559
 0.956483   0.386263  0.913086
 0.688278   0.827451  0.775269
 0.609029   0.779431  0.956487

In [94]:
arr2d[[true, false, true, true, false], 3:5]

3×3 Array{Float64,2}:
 0.0104643  0.232791  0.0600055
 0.956483   0.386263  0.913086
 0.688278   0.827451  0.775269

In [ ]:
arr2d[1, 1] = 0.0

In [ ]:
arr2d

In [95]:
arr2d[[true, false, true, true, false], 3:5] = ones(3, 3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [96]:
arr2d

5×5 Array{Float64,2}:
 0.544344  0.999666  1.0       1.0       1.0
 0.964799  0.811172  0.686232  0.6783    0.458559
 0.332513  0.531909  1.0       1.0       1.0
 0.481364  0.288425  1.0       1.0       1.0
 0.428898  0.863212  0.609029  0.779431  0.956487

In [97]:
for person in ["Alison", "James", "Cohen"]
    println("Hello $person")
end

Hello Alison
Hello James
Hello Cohen


In [98]:
people = ["Alison", "James", "Cohen"]

3-element Array{String,1}:
 "Alison"
 "James"
 "Cohen"

In [99]:
for i in eachindex(people)
    println("$i. $(people[i])")
end

1. Alison
2. James
3. Cohen


In [100]:
arr = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [101]:
push!(arr, 4)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [102]:
push!(arr, 5, 6, 7)

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7

In [103]:
pop!(arr)

7

In [104]:
deleteat!(arr, 3)

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

In [105]:
arr = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [106]:
arr2 = arr

3-element Array{Int64,1}:
 1
 2
 3

In [107]:
pop!(arr2)

3

In [108]:
arr2

2-element Array{Int64,1}:
 1
 2

In [109]:
arr

2-element Array{Int64,1}:
 1
 2

In [110]:
arr2 = copy(arr)

2-element Array{Int64,1}:
 1
 2

In [111]:
pop!(arr2)

2

In [112]:
arr

2-element Array{Int64,1}:
 1
 2

In [113]:
arr2

1-element Array{Int64,1}:
 1

In [114]:
[x += 1 for x = 1:5]

5-element Array{Int64,1}:
 2
 3
 4
 5
 6

In [115]:
Float64[x+=1 for x = 1:5]

5-element Array{Float64,1}:
 2.0
 3.0
 4.0
 5.0
 6.0

In [116]:
[x+=y for x = 1:5, y = 11:15]

5×5 Array{Int64,2}:
 12  13  14  15  16
 13  14  15  16  17
 14  15  16  17  18
 15  16  17  18  19
 16  17  18  19  20

In [117]:
[x += 1 for x = 1:10 if x/2 > 3]

4-element Array{Int64,1}:
  8
  9
 10
 11

In [118]:
(x+=1 for x = 1:10)

Base.Generator{UnitRange{Int64},var"#9#10"}(var"#9#10"(), 1:10)

In [119]:
for i in [x^3 for x=1:1_000_000]
   i >= 1_000 && break
   println(i)
end

1
8
27
64
125
216
343
512
729


In [120]:
@time for i in [x^3 for x=1:1_000_000]
   i >= 1_000 && break
   println(i)
end 

1
8
27
64
125
216
343
512
729
  0.042229 seconds (43.29 k allocations: 9.859 MiB)


In [121]:
@time for i in (x^3 for x=1:1_000_000)
   i >= 1_000 && break
   println(i)
end

1
8
27
64
125
216
343
512
729
  0.026552 seconds (13.83 k allocations: 788.207 KiB)


In [122]:
using Pkg
pkg"add RDatasets"

  Resolving package versions...
  Installed CodecZlib ─────────────────── v0.7.0
  Installed SortingAlgorithms ─────────── v0.3.1
  Installed Libiconv_jll ──────────────── v1.16.0+7
  Installed IteratorInterfaceExtensions ─ v1.0.0
  Installed Requires ──────────────────── v1.1.2
  Installed DataStructures ────────────── v0.18.8
  Installed PrettyTables ──────────────── v0.10.1
  Installed Reexport ──────────────────── v0.2.0
  Installed Compat ────────────────────── v3.25.0
  Installed PooledArrays ──────────────── v0.5.3
  Installed TranscodingStreams ────────── v0.9.5
  Installed ExprTools ─────────────────── v0.1.3
  Installed FileIO ────────────────────── v1.4.5
  Installed DataFrames ────────────────── v0.22.2
  Installed OrderedCollections ────────── v1.3.2
  Installed RDatasets ─────────────────── v0.7.3
  Installed Tables ────────────────────── v1.2.2
  Installed SentinelArrays ────────────── v1.2.16
  Installed RecipesBase ───────────────── v1.1.1
  Installed InvertedIndices ─

In [129]:
Pkg.add("DataFrames")

  Resolving package versions...
Updating `/content/Project.toml`
  [a93c6f00] + DataFrames v0.22.2
No Changes to `/content/Manifest.toml`


In [130]:
using DataFrames

In [123]:
using RDatasets

┌ Info: Precompiling RDatasets [ce6b1742-4840-55fa-b093-852dadbb1d8b]
└ @ Base loading.jl:1278


In [124]:
RDatasets.datasets()

763×5 DataFrame
 Row │ Package  Dataset      Title        Rows   Columns 
     │ String   String       String       Int64  Int64   
─────┼───────────────────────────────────────────────────
   1 │ COUNT    affairs      affairs        601       18
   2 │ COUNT    azdrg112     azdrg112      1798        4
   3 │ COUNT    azpro        azpro         3589        6
   4 │ COUNT    badhealth    badhealth     1127        3
   5 │ COUNT    fasttrakg    fasttrakg       15        9
   6 │ COUNT    lbw          lbw            189       10
   7 │ COUNT    lbwgrp       lbwgrp           6        7
   8 │ COUNT    loomis       loomis         410       11
   9 │ COUNT    mdvis        mdvis         2227       13
  10 │ COUNT    medpar       medpar        1495       10
  11 │ COUNT    rwm          rwm          27326        4
  ⋮  │    ⋮          ⋮            ⋮         ⋮       ⋮
 754 │ gamair   mpg          mpg            205       27
 755 │ gamair   prostate     prostate       654      530
 756 │ gamair   sitka        sitka         1027        6
 757 │ gamair   sole         sole          1575        8
 758 │ gamair   sperm.comp1  sperm.comp1     15        5
 759 │ gamair   sperm.comp2  sperm.comp2     24       11
 760 │ gamair   stomata      stomata         24        4
 761 │ gamair   swer         swer          2196       10
 762 │ gamair   wesdr        wesdr          669        5
 763 │ gamair   wine         wine            47        8
                                         742 rows omitted

In [197]:
iris = dataset("datasets", "iris")

150×5 DataFrame
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species   
     │ Float64      Float64     Float64      Float64     Cat…      
─────┼─────────────────────────────────────────────────────────────
   1 │         5.1         3.5          1.4         0.2  setosa
   2 │         4.9         3.0          1.4         0.2  setosa
   3 │         4.7         3.2          1.3         0.2  setosa
   4 │         4.6         3.1          1.5         0.2  setosa
   5 │         5.0         3.6          1.4         0.2  setosa
   6 │         5.4         3.9          1.7         0.4  setosa
   7 │         4.6         3.4          1.4         0.3  setosa
   8 │         5.0         3.4          1.5         0.2  setosa
   9 │         4.4         2.9          1.4         0.2  setosa
  10 │         4.9         3.1          1.5         0.1  setosa
  11 │         5.4         3.7          1.5         0.2  setosa
  ⋮  │      ⋮           ⋮            ⋮           ⋮           ⋮
 141 │         6.7         3.1          5.6         2.4  virginica
 142 │         6.9         3.1          5.1         2.3  virginica
 143 │         5.8         2.7          5.1         1.9  virginica
 144 │         6.8         3.2          5.9         2.3  virginica
 145 │         6.7         3.3          5.7         2.5  virginica
 146 │         6.7         3.0          5.2         2.3  virginica
 147 │         6.3         2.5          5.0         1.9  virginica
 148 │         6.5         3.0          5.2         2.0  virginica
 149 │         6.2         3.4          5.4         2.3  virginica
 150 │         5.9         3.0          5.1         1.8  virginica
                                                   129 rows omitted

In [126]:
names(iris)

5-element Array{String,1}:
 "SepalLength"
 "SepalWidth"
 "PetalLength"
 "PetalWidth"
 "Species"

In [127]:
size(iris)

(150, 5)

In [196]:
df = DataFrame(A = 1:2:1000, B = repeat(1:10, inner=50), C = 1:500)

500×3 DataFrame
 Row │ A      B      C     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      1
   2 │     3      1      2
   3 │     5      1      3
   4 │     7      1      4
   5 │     9      1      5
   6 │    11      1      6
   7 │    13      1      7
   8 │    15      1      8
   9 │    17      1      9
  10 │    19      1     10
  11 │    21      1     11
  ⋮  │   ⋮      ⋮      ⋮
 491 │   981     10    491
 492 │   983     10    492
 493 │   985     10    493
 494 │   987     10    494
 495 │   989     10    495
 496 │   991     10    496
 497 │   993     10    497
 498 │   995     10    498
 499 │   997     10    499
 500 │   999     10    500
           479 rows omitted

In [145]:
first(df, 4)

4×3 DataFrame
 Row │ A      B      C     
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      1      1
   2 │     3      1      2
   3 │     5      1      3
   4 │     7      1      4

In [ ]:
#head(iris) #- Not working

In [146]:
first(iris, 5)

5×5 DataFrame
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species 
     │ Float64      Float64     Float64      Float64     Cat…    
─────┼───────────────────────────────────────────────────────────
   1 │         5.1         3.5          1.4         0.2  setosa
   2 │         4.9         3.0          1.4         0.2  setosa
   3 │         4.7         3.2          1.3         0.2  setosa
   4 │         4.6         3.1          1.5         0.2  setosa
   5 │         5.0         3.6          1.4         0.2  setosa

In [147]:
last(iris, 5)

5×5 DataFrame
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species   
     │ Float64      Float64     Float64      Float64     Cat…      
─────┼─────────────────────────────────────────────────────────────
   1 │         6.7         3.0          5.2         2.3  virginica
   2 │         6.3         2.5          5.0         1.9  virginica
   3 │         6.5         3.0          5.2         2.0  virginica
   4 │         6.2         3.4          5.4         2.3  virginica
   5 │         5.9         3.0          5.1         1.8  virginica

In [ ]:
#tail(iris) - Not Working

In [207]:
#by(iris, :Species) # Not Working

LoadError: ignored

In [208]:
gd = groupby(iris, :Species)
#combine(groupby(iris, :Species))


#combine(map(d -> println(d[!, ["SepalLength",	"SepalWidth",	"PetalLength"]]), gd))
#combine(iris, :Species)

GroupedDataFrame with 3 groups based on key: Species
First Group (50 rows): Species = CategoricalArrays.CategoricalValue{String,UInt8} "setosa"
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species 
     │ Float64      Float64     Float64      Float64     Cat…    
─────┼───────────────────────────────────────────────────────────
   1 │         5.1         3.5          1.4         0.2  setosa
   2 │         4.9         3.0          1.4         0.2  setosa
   3 │         4.7         3.2          1.3         0.2  setosa
   4 │         4.6         3.1          1.5         0.2  setosa
   5 │         5.0         3.6          1.4         0.2  setosa
   6 │         5.4         3.9          1.7         0.4  setosa
   7 │         4.6         3.4          1.4         0.3  setosa
   8 │         5.0         3.4          1.5         0.2  setosa
   9 │         4.4         2.9          1.4         0.2  setosa
  10 │         4.9         3.1          1.5         0.1  setosa
  11 │         5.4         3.7          1.5         0.2  setosa
  ⋮  │      ⋮           ⋮            ⋮           ⋮          ⋮
  40 │         5.1         3.4          1.5         0.2  setosa
  41 │         5.0         3.5          1.3         0.3  setosa
  42 │         4.5         2.3          1.3         0.3  setosa
  43 │         4.4         3.2          1.3         0.2  setosa
  44 │         5.0         3.5          1.6         0.6  setosa
  45 │         5.1         3.8          1.9         0.4  setosa
  46 │         4.8         3.0          1.4         0.3  setosa
  47 │         5.1         3.8          1.6         0.2  setosa
  48 │         4.6         3.2          1.4         0.2  setosa
  49 │         5.3         3.7          1.5         0.2  setosa
  50 │         5.0         3.3          1.4         0.2  setosa
                                                  28 rows omitted
⋮
Last Group (50 rows): Species = CategoricalArrays.CategoricalValue{String,UInt8} "virginica"
 Row │ SepalLength  SepalWidth  PetalLength  PetalWidth  Species   
     │ Float64      Float64     Float64      Float64     Cat…      
─────┼─────────────────────────────────────────────────────────────
   1 │         6.3         3.3          6.0         2.5  virginica
   2 │         5.8         2.7          5.1         1.9  virginica
   3 │         7.1         3.0          5.9         2.1  virginica
   4 │         6.3         2.9          5.6         1.8  virginica
   5 │         6.5         3.0          5.8         2.2  virginica
   6 │         7.6         3.0          6.6         2.1  virginica
   7 │         4.9         2.5          4.5         1.7  virginica
   8 │         7.3         2.9          6.3         1.8  virginica
   9 │         6.7         2.5          5.8         1.8  virginica
  10 │         7.2         3.6          6.1         2.5  virginica
  11 │         6.5         3.2          5.1         2.0  virginica
  ⋮  │      ⋮           ⋮            ⋮           ⋮           ⋮
  40 │         6.9         3.1          5.4         2.1  virginica
  41 │         6.7         3.1          5.6         2.4  virginica
  42 │         6.9         3.1          5.1         2.3  virginica
  43 │         5.8         2.7          5.1         1.9  virginica
  44 │         6.8         3.2          5.9         2.3  virginica
  45 │         6.7         3.3          5.7         2.5  virginica
  46 │         6.7         3.0          5.2         2.3  virginica
  47 │         6.3         2.5          5.0         1.9  virginica
  48 │         6.5         3.0          5.2         2.0  virginica
  49 │         6.2         3.4          5.4         2.3  virginica
  50 │         5.9         3.0          5.1         1.8  virginica
                                                    28 rows omitted

In [209]:
describe(iris)

5×7 DataFrame
 Row │ variable     mean     min     median  max        nmissing  eltype       ⋯
     │ Symbol       Union…   Any     Union…  Any        Int64     DataType     ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ SepalLength  5.84333  4.3     5.8     7.9               0  Float64      ⋯
   2 │ SepalWidth   3.05733  2.0     3.0     4.4               0  Float64
   3 │ PetalLength  3.758    1.0     4.35    6.9               0  Float64
   4 │ PetalWidth   1.19933  0.1     1.3     2.5               0  Float64
   5 │ Species               setosa          virginica         0  CategoricalV ⋯
                                                                1 column omitted

In [213]:
#describe(iris, stats=[:q25, :q75, :first, :last])

In [215]:
#describe(iris, stats=:all)

In [217]:
using Statistics
mean(iris[!,:SepalLength])

5.843333333333334

In [ ]:
median(iris[:SepalLength])

In [ ]:
std(iris[:SepalLength])

In [ ]:
for x in names(iris)[1:end-1]   
	    for y in names(iris)[1:end-1]
	      println("$x \t $y \t $(cor(iris[x], iris[y]))")
	    end
	    println("-------------------------------------------")
	  end

In [ ]:
for x in names(iris)[1:end-1]
         for y in names(iris)[1:end-1]
           println("$x \t $y \t $(cov(iris[x], iris[y]))")
         end
         println("--------------------------------------------")
       end

In [ ]:
rand(iris[:SepalLength])

In [ ]:
rand(iris[:SepalLength], 5)

In [ ]:
sepallength = Array(iris[:SepalLength])

In [ ]:
irisarr = convert(Array, iris[:,:])

In [ ]:
pkg"add Compose#master"
pkg"add Gadfly#master"
pkg"add Hexagons"
# pkg"add Gadfly"
using Gadfly

In [ ]:
plot(iris, x=:SepalLength, y=:PetalLength, color=:Species)

In [ ]:
plot(iris, x=:Species, y=:PetalLength, Geom.boxplot)

In [ ]:
plot(iris, x=:PetalLength, color=:Species, Geom.histogram)

In [ ]:
plot(iris, x=:PetalWidth, color=:Species, Geom.histogram)

In [ ]:
plot(iris, x=:PetalWidth, y=:PetalLength, color=:Species)

In [ ]:
iris[1:3, [:PetalLength, :PetalWidth]]

In [ ]:
iris[trues(150), [:PetalLength, :PetalWidth]]

In [ ]:
test_data = iris[rand(150) .<= 0.1, [:PetalLength, :PetalWidth, :Species]]

In [ ]:
pkg"add CSV"

In [ ]:
using CSV

In [ ]:
CSV.write("test_data.csv", test_data)

In [ ]:
pkg"add Feather"

In [ ]:
using Feather

In [ ]:
Feather.write("test_data.feather", test_data)

In [ ]:
Feather.read("test_data.feather")